# Generated by Django 5.0.1 on 2024-01-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizABL1', '0003_alter_customuser_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizABL1.city'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizABL1.department'),
        ),
    ]
