# Generated by Django 5.0.1 on 2024-01-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizABL1', '0004_alter_customuser_city_alter_customuser_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='quiz_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
