# Generated by Django 5.0.1 on 2024-01-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizABL1', '0005_alter_customuser_user_id_alter_question_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizABL1.quizsession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizsession',
            name='creator',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizsession',
            name='subject',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
