# Generated by Django 5.0.1 on 2024-02-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizABL1', '0007_remove_question_options_question_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='submit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
